In [1]:
import pandas as pd

data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=";")

In [3]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [12]:
data.shape

(1599, 12)

In [9]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(data)        # shor for same X train and y tran

In [10]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
785,9.9,0.350,0.41,2.3,0.083,11.0,61.0,0.99820,3.21,0.50,9.5,5
189,7.9,0.490,0.32,1.9,0.082,17.0,144.0,0.99680,3.20,0.55,9.5,5
919,8.4,0.620,0.12,1.8,0.072,38.0,46.0,0.99504,3.38,0.89,11.8,6
996,5.6,0.660,0.00,2.2,0.087,3.0,11.0,0.99378,3.71,0.63,12.8,7
1034,8.9,0.745,0.18,2.5,0.077,15.0,48.0,0.99739,3.20,0.47,9.7,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,6.4,0.420,0.09,2.3,0.054,34.0,64.0,0.99724,3.41,0.68,10.4,6
268,6.9,0.540,0.04,3.0,0.077,7.0,27.0,0.99870,3.69,0.91,9.4,6
1451,7.8,0.320,0.44,2.7,0.104,8.0,17.0,0.99732,3.33,0.78,11.0,7
253,7.7,0.775,0.42,1.9,0.092,8.0,86.0,0.99590,3.23,0.59,9.5,5
1067,11.1,0.310,0.53,2.2,0.060,3.0,10.0,0.99572,3.02,0.83,10.9,7

In [11]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1227,9.0,0.580,0.25,2.0,0.104,8.0,21.0,0.99769,3.27,0.72,9.60,5
37,8.1,0.380,0.28,2.1,0.066,13.0,30.0,0.99680,3.23,0.73,9.70,7
1541,7.4,0.250,0.29,2.2,0.054,19.0,49.0,0.99666,3.40,0.76,10.90,7
28,7.1,0.710,0.00,1.9,0.080,14.0,35.0,0.99720,3.47,0.55,9.40,5
1396,8.7,0.675,0.10,1.6,0.090,4.0,11.0,0.99745,3.31,0.65,9.55,5
...,...,...,...,...,...,...,...,...,...,...,...,...
799,9.4,0.500,0.34,3.6,0.082,5.0,14.0,0.99870,3.29,0.52,10.70,6
1170,9.2,0.360,0.34,1.6,0.062,5.0,12.0,0.99667,3.20,0.67,10.50,6
160,7.6,0.950,0.03,2.0,0.090,7.0,20.0,0.99590,3.20,0.56,9.60,5
564,13.0,0.470,0.49,4.3,0.085,6.0,47.0,1.00210,3.30,0.68,12.70,6
233,6.9,0.520,0.25,2.6,0.081,10.0,37.0,0.99685,3.46,0.50,11.00,5